language: node_js

node_js:
- node
- '6'
- '4'

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

script:
- yarn run lint
- yarn run flow
- yarn run test

after_failure:
- "(cd resources; python travis_after_all.py)"

after_success:
- "(cd resources; python travis_after_all.py)"
- export $(cat resources/.to_export_back)

deploy:
  provider: npm
  email: jacobwgillespie@gmail.com
  api_key:
    secure: HdjDzyh/M6SN4wM8macctTUTr438wOGq6S0mkNEgwBQ0aPM1AqQ3uuI8C6AkS+0YiDS9DD8429n+c55UrPMFlmx5JNe56FTOrwTvWHzG53GB66Tm10Zv+mGVciKcQK5CEBUVLffznpyTS07sb7RFJN8BBAIACp5G18G0+Gd3JxKvsYlXD7/hDIqR72tqSYkzlX1rNXJLKG3X39t05ss9V10JYcfR3joXgIryIUS1/qbiKCckZ+61odgpwEm222HEdfOERbRz4I8VP+WuT29idfpEjVv5D++7GaYlUOjno3QiPi1QxRQkJEnBnAl9/6l+LHm4po01Wmaa8MTMsSJT9HW3Atw06VHcY5qzaGk2zZ1BXLGjmKHSGRj7QgzK5vY00DWM0/N+GJJM8COKCtNGoWVv2ogclRSuYumDl1JL+3gwkz5kqkUMOY9n1JDZJqXMkWfAe10QSWpYK7LG1+6yVLpfjcQB2q+DtiU91pB7gz5b7JTUZHNkr7WYkCqkPotoQ9XMQXSgBBFnX/rg2FcEZO4WKsMUuxzeRylhMgm9NVvDKZx7wHhZy+GrneYBbjNkSDC+jqK4ZSU/MLufU0ISZ3l7GjFRiWL0c99QScYEHlo7DINRmrDTV1n4mih15iBJqp9Z+DnF+WbHUZ29usc+BYHhvOZcwyZGHVQAXnceRZY=
  on:
    tags: true
    repo: jacobwgillespie/plex-sync
    branch: master
    condition: "$BUILD_LEADER$BUILD_AGGREGATE_STATUS = YESothers_succeeded"
